steam_friends/views/auth.py
from __future__ import absolute_import, print_function

from flask.ext import openid
import flask

from steam_friends import ext, models


blueprint = flask.Blueprint('auth', __name__)


@ext.oid.after_login
def after_login(resp):
    flask.session['openid'] = resp.identity_url
    steamid = models.SteamUser.id_from_openid(resp.identity_url)
    flask.g.steamid = steamid

    # todo: if we change the index page to not do any fetching and move that js, queue_friends_of_friends=True
    flask.g.steam_user = u = models.SteamUser.get_user(steamid, queue_friends_of_friends=False)
    flask.flash('Welcome, {}! Your steamid is {}'.format(u.personaname, u.steamid), 'info')
    return flask.redirect(ext.oid.get_next_url())


@blueprint.route('/login', methods=['GET', 'POST'])
@ext.oid.loginhandler
def login():
    if flask.g.steam_user is not None:
        return flask.redirect(ext.oid.get_next_url())
    if flask.request.method == 'POST':
        url = openid.COMMON_PROVIDERS['steam']  # 'https://steamcommunity.com/openid'
        return ext.oid.try_login(url)  # 'http://steamcommunity.com/openid')
    return flask.render_template(
        'login.html',
        next=ext.oid.get_next_url(),
        error=ext.oid.fetch_error(),
    )


@blueprint.route('/logout')
def logout():
    flask.session.pop('openid', None)
    flask.flash(u'You were signed out', 'info')
    return flask.redirect(ext.oid.get_next_url())


@blueprint.before_app_request
def lookup_current_user():
    flask.g.steam_user = None
    if 'openid' in flask.session:
        steamid = models.SteamUser.id_from_openid(flask.session['openid'])
        flask.g.steamid = steamid
        flask.g.steam_user = models.SteamUser.get_user(steamid)


@ext.oid.errorhandler
def on_error(message):
    flask.flash(u'Login Error: ' + message, 'warning')

steam_friends/templates/index.html
{% extends "layout.html" %}

{% block title %}Steam Friends{% endblock %}

{% block body %}
<h1>Steam Friends!</h1>

{% if g.steam_user == None %}
  <form action="{{ url_for('auth.login') }}" method="post">
    <input class="btn btn-default" type="submit" value="Login with Steam">
    <input type="hidden" name="action" value="login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>
{% else %}
  <a class="btn btn-default" href="{{ url_for('auth.logout') }}">Logout {{ g.steam_user }}</a>
{% endif %}

<p>This was really just a quick prototype. If you want to help make a better UI for this, please open an issue or pull request on <a href="https://github.com/WyseNynja/steam_friends">GitHub</a>.</p>

<form method="GET">
  <textarea class="form-control" name="ids_and_names" placeholder="Space-separated list of steamids (the profile name on steamcommunity.com, not the login or display name) or steamid64s" rows="2">{{ passed_ids }}</textarea>
  <button type="submit" class="btn btn-default">Compare These Users</button>
</form>

{# todo: put this in a macro #}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="table-responsive">
  <table id="steamGames" class="table table-hover tablesorter">
    <thead>
      <tr>
        <th>Game</th>
        <th>Owners</th>
        {% for u in steam_users %}
          <th>
              <img alt="{{ u.steamid }}" class="img-thumbnail pull-left" src="{{ u.avatar }}" />
              {{ u }}
          </th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
    {% for g, c in game_counter.most_common() %}
      {% if c == steam_users | length %}
        {% set tr_class="success" %}
      {% elif c == 1 and steam_users | length > 2 %}
        {% set tr_class="warning" %}
      {% else %}
        {% set tr_class="" %}
      {% endif %}
      <tr class="{{ tr_class }}">
        <td><img class="img-thumbnail pull-left" src="{{ g.img_icon_url }}" />{{ g.name }}</td>
        <td>{{ c }}</td>
        {% for u in steam_users %}
          <td>
            {% if g in u.games %}
              <span class="glyphicon glyphicon-play"></span>
            {% else %}
              <span class="glyphicon glyphicon-download"></span>
            {% endif %}
          </td>
        {% endfor %}
      </tr>
    {% else %}
      <tr class="danger">
        <td colspan="{{ 2 + steam_users | length }}">No games found :(</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

<div class="table-responsive">
  <table id="steamFriends" class="table table-hover tablesorter">
    <thead>
      <tr>
        <th>Friends</th>
        <th>#</th>
        {% for u in steam_users %}
          <th>
              <img alt="{{ u.steamid }}" class="img-thumbnail pull-left" src="{{ u.avatar }}" />
              {{ u }}
          </th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
    {% for f, c in friend_counter.most_common() %}
      {% if c == steam_users | length %}
        {% set tr_class="success" %}
      {% elif c == 1 and steam_users | length > 2 %}
        {% set tr_class="warning" %}
      {% else %}
        {% set tr_class="" %}
      {% endif %}
      <tr class="{{ tr_class }}">
        <td>
          <img alt="{{ f.steamid }}" class="img-thumbnail pull-left" src="{{ f.avatar }}" />
          {{ f.personaname }} ({{ f.steamid }})
        </td>
        <td>{{ c }}</td>
        {% for u in steam_users %}
          <td>
            {% if f in u.friends %}
              <span class="glyphicon glyphicon-user"></span>
            {% else %}
              <span class="glyphicon glyphicon-remove"></span>
            {% endif %}
          </td>
        {% endfor %}
      </tr>
    {% else %}
      <tr class="danger">
        <td colspan="{{ 2 + steam_users | length }}">No friends found :(</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block javascript %}
<script src="https://raw.githubusercontent.com/christianbach/tablesorter/master/jquery.tablesorter.min.js"></script>
<script src="https://raw.githubusercontent.com/markmalek/Fixed-Header-Table/master/jquery.fixedheadertable.min.js"></script>
<script>
  $(document).ready(function() {
    $("#steamGames").tablesorter();
    $("#steamFriends").tablesorter();
  });
</script>
{% endblock %}

steam_friends/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Steam Friends{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

<div class="container-fluid">
{% block body %}{% endblock %}
</div>

<div class="container-fluid footer">
  <a href="http://steampowered.com" target="_blank">Powered by Steam</a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
{% block javascript %}{% endblock %}

</body>
</html>

steam_friends/templates/login.html
{% extends "layout.html" %}

{% block title %}Steam Friends - Sign in{% endblock %}

{% block body %}
<h2>Sign in</h2>

{# todo: put this in a macro #}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

<form action="" method=post>
  <input type=submit value="Sign in">
  <input type=hidden name=next value="{{ next }}">
</form>

<!-- http://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_small.png -->

{% endblock %}